strategy:
  name: FxCotContrarianTS
  universe: [EURUSD, USDJPY, GBPUSD, USDCAD, USDCHF, AUDUSD, NZDUSD, USDMXN]
  params: {}
dates:
  start: "2011-01-01"
  end: "2026-04-30"
backtest:
  initial_capital: 1000000
  vol_target_per_instrument: 0.03
  idm: true
  rebalance: weekly
