last_modified: '2026-02-25T00:42:34.771951-05:00'
modified_by: api
strategies:
  cscm:
    enabled: false
    shutdown_requested: false
  mp:
    enabled: true
    shutdown_requested: false
  omr:
    enabled: true
    shutdown_requested: false
  ramp:
    enabled: true
    shutdown_requested: false
