last_modified: '2026-03-19T01:08:14.909806-04:00'
modified_by: api
strategies:
  cscm:
    enabled: false
    shutdown_requested: false
  mp:
    enabled: true
    shutdown_requested: false
  omr:
    enabled: true
    shutdown_requested: false
  ramp:
    enabled: true
    shutdown_requested: false
