"""Render IBC config.ini from .env credentials.

Replaces setup_ibc_config.bat -- handles special characters in passwords
that break batch variable expansion.

Creates: %USERPROFILE%\\Documents\\IBC\\config.ini

Usage:
    python infra/local/setup_ibc_config.py
"""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def load_env(env_path: Path) -> dict:
    """Parse KEY=VALUE lines from .env, stripping quotes."""
    if not env_path.exists():
        print(f"[X] .env not found at {env_path}")
        sys.exit(1)

    env = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        val = val.strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        env[key.strip()] = val
    return env


def main():
    env = load_env(PROJECT_ROOT / ".env")

    username = env.get("IBKR_USERNAME", "")
    password = env.get("IBKR_PASSWORD", "")
    trading_mode = env.get("IBKR_TRADING_MODE", "paper")
    gateway_port = env.get("IBKR_GATEWAY_PORT", "4002")

    if not username:
        print("[X] IBKR_USERNAME not set in .env")
        sys.exit(1)
    if not password:
        print("[X] IBKR_PASSWORD not set in .env")
        sys.exit(1)

    ibc_dir = Path(os.environ["USERPROFILE"]) / "Documents" / "IBC"
    ibc_dir.mkdir(parents=True, exist_ok=True)

    ini_path = ibc_dir / "config.ini"
    ini_content = f"""\
# Generated by setup_ibc_config.py -- do not edit directly.
# Source: config/ibkr/ibc-config.ini.template

LogToConsole=yes
FIX=no

IbLoginId={username}
IbPassword={password}
TradingMode={trading_mode}

AcceptIncomingConnectionAction=accept
ClosedownAt=
AcceptNonBrokerageAccountWarning=yes
ExistingSessionDetectedAction=primary
JavaHeapSize=512
OverrideTwsApiPort={gateway_port}

SecondFactorAuthenticationTimeout=180
ReloginAfterSecondFactorAuthenticationTimeout=yes
ReadOnlyApi=no
"""
    ini_path.write_text(ini_content, encoding="utf-8")

    print(f"[+] Written: {ini_path}")
    print(f"    Mode: {trading_mode}")
    print(f"    Port: {gateway_port}")


if __name__ == "__main__":
    main()
