@echo off
REM Render IBC config from template using .env credentials.
REM Creates: %USERPROFILE%\Documents\IBC\config.ini
REM          %USERPROFILE%\Documents\IBC\start_tws.bat

setlocal enabledelayedexpansion

REM Load .env from project root
set "PROJECT_ROOT=%~dp0..\.."
call :load_env "%PROJECT_ROOT%\.env"
if errorlevel 1 (
    echo [X] Failed to load .env -- copy .env.example to .env and fill in IBKR credentials.
    exit /b 1
)

REM Validate required vars
if "%IBKR_USERNAME%"=="" (
    echo [X] IBKR_USERNAME not set in .env
    exit /b 1
)
if "%IBKR_PASSWORD%"=="" (
    echo [X] IBKR_PASSWORD not set in .env
    exit /b 1
)
if "%IBKR_TRADING_MODE%"=="" set "IBKR_TRADING_MODE=paper"
if "%IBKR_GATEWAY_PORT%"=="" set "IBKR_GATEWAY_PORT=4002"

REM Create config directory
if not exist "%USERPROFILE%\Documents\IBC" mkdir "%USERPROFILE%\Documents\IBC"

REM Render config.ini from template
echo [+] Rendering IBC config...
set "INI=%USERPROFILE%\Documents\IBC\config.ini"
(
    echo # Generated by setup_ibc_config.bat -- do not edit directly.
    echo # Source: config\ibkr\ibc-config.ini.template
    echo.
    echo LogToConsole=yes
    echo FIX=no
    echo.
    echo IbLoginId=%IBKR_USERNAME%
    echo IbPassword=%IBKR_PASSWORD%
    echo TradingMode=%IBKR_TRADING_MODE%
    echo.
    echo AcceptIncomingConnectionAction=accept
    echo ClosedownAt=
    echo AcceptNonBrokerageAccountWarning=yes
    echo ExistingSessionDetectedAction=primary
    echo JavaHeapSize=512
    echo OverrideTwsApiPort=%IBKR_GATEWAY_PORT%
    echo.
    echo SecondFactorAuthenticationTimeout=180
    echo ReloginAfterSecondFactorAuthenticationTimeout=yes
    echo ReadOnlyApi=no
) > "%INI%"

echo     Written: %INI%
echo     Mode: %IBKR_TRADING_MODE%
echo     Port: %IBKR_GATEWAY_PORT%
echo.

REM Detect TWS version
set "TWS_VRSN="
for /d %%D in (C:\Jts\*) do (
    if exist "%%D\jars" set "TWS_VRSN=%%~nxD"
)
if "%TWS_VRSN%"=="" (
    echo [!] Could not detect TWS version in C:\Jts -- install TWS offline first.
    echo     Download: https://www.interactivebrokers.com/en/trading/tws-offline-installers.php
    exit /b 1
)
echo [+] Detected TWS version: %TWS_VRSN%

REM Create launcher
echo [+] Creating start_tws.bat...
set "LAUNCHER=%~dp0start_tws.bat"
(
    echo @echo off
    echo REM Launch TWS via IBC. Generated by setup_ibc_config.bat.
    echo set "TWS_MAJOR_VRSN=%TWS_VRSN%"
    echo set "IBC_INI=%USERPROFILE%\Documents\IBC\config.ini"
    echo set "IBC_PATH=C:\IBC"
    echo C:\IBC\scripts\StartTWS.bat
) > "%LAUNCHER%"
echo     Written: %LAUNCHER%
echo.

echo [+] Setup complete. Run: infra\local\start_tws.bat
goto :eof

:load_env
REM Parse KEY=VALUE lines from .env (strips quotes)
if not exist "%~1" (
    echo [X] .env not found at %~1
    exit /b 1
)
for /f "usebackq tokens=1,* delims==" %%A in ("%~1") do (
    set "line=%%A"
    if not "!line:~0,1!"=="#" (
        set "val=%%B"
        REM Strip surrounding quotes
        if "!val:~0,1!"==^""" set "val=!val:~1,-1!"
        set "%%A=!val!"
    )
)
goto :eof
