"""Macro event calendar loader for FOMC/NFP/CPI release dates.

Each event type has a corresponding YAML at config/macro_calendar/<type>.yaml
with structure:

    event_type: fomc
    description: ...
    dates:
      - 2024-01-31
      - 2024-03-20
      ...

Use this when a strategy needs to gate trading on macro events (e.g., skip
new entries on FOMC days, widen stops 2 days before NFP, etc.).

The YAMLs are regenerated by scripts/data/generate_macro_calendar_yamls.py
when the published schedules change.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

VALID_EVENT_TYPES = ("fomc", "nfp", "cpi")
_DEFAULT_CALENDAR_DIR = Path(__file__).resolve().parents[4] / "config" / "macro_calendar"


def load_macro_calendar(
    event_type: str,
    calendar_dir: Path | None = None,
) -> list[date]:
    """Load a list of event dates for the given event type.

    Args:
        event_type: One of "fomc", "nfp", "cpi".
        calendar_dir: Optional override for the YAML directory (for testing
            or non-default deployments).

    Returns:
        Sorted list of `date` objects.

    Raises:
        ValueError: If event_type is not recognized.
        FileNotFoundError: If the YAML file doesn't exist.
        ValueError: If the YAML structure is malformed.
    """
    if event_type not in VALID_EVENT_TYPES:
        raise ValueError(
            f"unknown event_type: {event_type!r}; "
            f"must be one of {VALID_EVENT_TYPES}"
        )

    cal_dir = calendar_dir if calendar_dir is not None else _DEFAULT_CALENDAR_DIR
    path = cal_dir / f"{event_type}.yaml"
    if not path.exists():
        raise FileNotFoundError(f"calendar not found: {path}")

    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict) or "dates" not in data:
        raise ValueError(f"malformed calendar (missing 'dates' key): {path}")
    if data.get("event_type") != event_type:
        raise ValueError(
            f"calendar event_type mismatch in {path}: "
            f"file says {data.get('event_type')!r}, expected {event_type!r}"
        )

    raw_dates = data["dates"]
    if not isinstance(raw_dates, list):
        raise ValueError(f"'dates' must be a list in {path}")

    out: list[date] = []
    for d in raw_dates:
        if isinstance(d, date):
            out.append(d)
        elif isinstance(d, str):
            out.append(date.fromisoformat(d))
        else:
            raise ValueError(f"unparseable date entry in {path}: {d!r}")

    return sorted(out)
