"""Emit a BLIND-SAFE ledger for strategy generation in a fresh context.

The generator must never see out-of-sample returns. If it does, candidate
selection becomes conditioned on results and the "pre-registration" is a
rationalisation. The campaign post-mortem admitted this exact breach: it
analysed the results and generated candidates in one context.

So the generator cannot be handed `FX_60_CATALOG_TRACKER.md`. That file's Notes
column is dense with OOS Sharpes, DSRs and PBOs. This script strips the tracker
to the facts a generator legitimately needs -- which slots are taken, what each
one needs to run, and what the apparatus can now do -- and nothing else.

Exposed: catalog id, name, capability tag, whether the slot is TESTED, and if so
whether the idea is dead across forms (REJECT) or only its naive form was tried
(FAIL-NAIVE, i.e. an enhanced form remains open).

Withheld, deliberately:
  - every Sharpe, DSR, PSR, PBO, cost figure and window
  - the entire Notes column
  - the WEAK grade. WEAK is collapsed into TESTED-FAIL because "this one nearly
    passed" is precisely the signal that invites a generator to aim at the
    near-miss. The generator needs "tested and did not pass", not a ranking.

Usage: PYTHONPATH=$(pwd) python scripts/strategy/build_generation_ledger.py
"""
from __future__ import annotations

import re
from pathlib import Path

from src.backtesting.statistics.dsr import expected_max_sharpe
from src.backtesting.walkforward_common import get_campaign_trial_distribution
from src.utils import logger

TRACKER = Path("docs/strategies/FX_60_CATALOG_TRACKER.md")
OUT = Path("docs/strategies/research/20260726_fx_generation_ledger.md")
PLANNED_SLATE_SIZE = 50

# Gate grade -> what the generator is allowed to know.
_GRADE = {
    "-": "OPEN",
    "": "OPEN",
    "REJECT": "TESTED-DEAD",        # killed across forms
    "FAIL": "TESTED-FAIL",
    "FAIL(cost-robust)": "TESTED-FAIL",
    "FAIL-enh": "TESTED-FAIL",      # enhanced form tried and failed
    "FAIL-NAIVE": "TESTED-NAIVE-ONLY",
    "FAIL-naive": "TESTED-NAIVE-ONLY",
    "WEAK": "TESTED-FAIL",          # collapsed on purpose, see module docstring
    "PASS": "PASSED",
}


def parse_rows(text: str) -> list[dict]:
    rows = []
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 8 or not re.fullmatch(r"\d+", cells[0]):
            continue
        grade = _GRADE.get(cells[6], "OPEN")
        rows.append({"id": int(cells[0]), "name": cells[1], "capability": cells[2],
                     "needs": cells[3], "status": grade})
    return sorted(rows, key=lambda r: r["id"])


def render(rows: list[dict], sr_zero: float, n_trials: int) -> str:
    open_rows = [r for r in rows if r["status"] == "OPEN"]
    naive = [r for r in rows if r["status"] == "TESTED-NAIVE-ONLY"]
    closed = [r for r in rows if r["status"] in ("TESTED-FAIL", "TESTED-DEAD")]
    by_cap: dict[str, int] = {}
    for r in open_rows:
        by_cap[r["capability"]] = by_cap.get(r["capability"], 0) + 1

    out = [
        "# FX Generation Ledger (blind-safe)",
        "",
        "Generated by `scripts/strategy/build_generation_ledger.py`. This is the",
        "ONLY campaign input a strategy generator may read. It deliberately",
        "contains no Sharpe, DSR, PSR, PBO or cost figure from any completed run.",
        "",
        "## The bar you must clear",
        "",
        f"- Trials consumed to date: **N = {n_trials}**",
        f"- Planned slate this wave: **{PLANNED_SLATE_SIZE}**",
        f"- Deflated bar at N + slate: **SR_zero = {sr_zero:.4f}** annualized",
        "",
        "Every spec must publish its best-case-if-true Sharpe against that bar",
        "BEFORE it consumes a trial (`src/backtesting/validation/viability.py`,",
        "`screen_spec`). A spec whose if-true Sharpe cannot clear the bar is",
        "arithmetically incapable of passing and must be routed to the",
        "forward-paper queue or into the combination spec instead.",
        "",
        "State `gross_edge_bps` and `per_trade_vol_bps` explicitly and honestly.",
        "Do NOT state a cost: the screen computes it from the measured",
        "hour-of-week spread surface for the pairs and hours you name.",
        "",
        "## Slot status",
        "",
        f"- OPEN (never tested): **{len(open_rows)}**",
        f"- TESTED-NAIVE-ONLY (naive form failed; an enhanced form is still open): **{len(naive)}**",
        f"- TESTED-FAIL / TESTED-DEAD (do not re-propose): **{len(closed)}**",
        "",
        "### OPEN slots by capability needed",
        "",
        "| capability | open slots |",
        "|---|---:|",
    ]
    out += [f"| {k} | {v} |" for k, v in sorted(by_cap.items(), key=lambda kv: -kv[1])]
    out += ["", "### Full slot table", "",
            "| # | name | capability | status |", "|---|---|---|---|"]
    out += [f"| {r['id']} | {r['name']} | {r['capability']} | {r['status']} |"
            for r in rows]
    out += [
        "",
        "## What the apparatus can now do",
        "",
        "Facts about capability, not about results.",
        "",
        "- **Intraday**: minute-bar order engine exists (stop/limit/OCO/bracket,",
        "  partial fills, trailing stops, no-lookahead). 1m OHLCV for 80 pairs,",
        "  2011-2026, on local disk.",
        "- **Costs**: MEASURED hour-of-week round-trip spread surface for 25",
        "  pairs. Majors in liquid hours are far cheaper than the retired pip-tier",
        "  model assumed, and illiquid hours far dearer. EURGBP and GBPJPY are not",
        "  directly quoted anywhere we hold, so they are DERIVED from their measured",
        "  USD legs (a synthetic cross is the sum of its legs); that over-charges",
        "  slightly, since a directly-quoted cross is tighter. Any pair outside",
        "  those 27 gets a flat hourly shape.",
        "- **Events**: authoritative US CPI / NFP / FOMC release timestamps,",
        "  DST-correct, validated against our own 1m data. FOMC covers 2013+ only.",
        "  Non-US central banks are NOT stamped and cannot support event-time work.",
        "- **Execution styles**: spread-TAKER only. A maker variant is not",
        "  backtestable on the data we hold; treat liquidity provision as a",
        "  forward-validation track, never a historical trial.",
        "- **Frequencies available**: 1m, and any aggregation of it, plus daily.",
        "",
        "## Rules for this wave",
        "",
        "1. Do not propose anything in a TESTED-FAIL or TESTED-DEAD slot.",
        "2. A TESTED-NAIVE-ONLY slot may be re-proposed ONLY as a genuinely",
        "   different functional form, with the mechanism stated. Re-running the",
        "   same idea with a tuned parameter is not a new spec.",
        "3. Every spec states its economic mechanism BEFORE its rule, and names",
        "   the falsifier that would kill it.",
        "4. Parameters are fixed at proposal time. No sweeps.",
        "5. Publish the viability screen result for every spec.",
        "",
        "## What you are not being told, and why",
        "",
        "No completed run's score appears here. You cannot know which failures",
        "were narrow and which were catastrophic, and that is intentional: aiming",
        "at a near-miss is how a search launders an old result into a new",
        "'hypothesis'. Propose from mechanism and from the open-slot map only.",
    ]
    return "\n".join(out) + "\n"


def main() -> None:
    rows = parse_rows(TRACKER.read_text(encoding="utf-8"))
    n_trials, sharpes = get_campaign_trial_distribution()
    sr_zero = expected_max_sharpe(sharpes, n_trials + PLANNED_SLATE_SIZE)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(rows, sr_zero, n_trials), encoding="utf-8")
    logger.success(f"[ledger] wrote {OUT}: {len(rows)} slots, N={n_trials}, "
                   f"SR_zero={sr_zero:.4f}")


if __name__ == "__main__":
    main()
