"""FX Wave 3 slate definitions. Screened, not hand-typed.

per_trade_vol_bps values are MEASURED from the held 1m data (scratchpad
measure_vol.py / measure_event_vol.py). gross_edge_bps values are literature or
first-principles estimates stated at proposal time. No signed effect was
measured before proposing -- only dispersion.
"""

WD = lambda hs: [d * 24 + h for d in range(5) for h in hs]

MAJ6 = ["EURUSD", "USDJPY", "GBPUSD", "AUDUSD", "USDCAD", "USDCHF"]
MAJ4 = ["EURUSD", "USDJPY", "GBPUSD", "USDCHF"]
G10 = MAJ6 + ["NZDUSD", "EURJPY", "AUDJPY", "EURCHF"]
COMMOD = ["AUDUSD", "NZDUSD", "USDCAD"]
JPYX = ["USDJPY", "EURJPY", "AUDJPY", "CHFJPY", "NZDJPY"]
NORDIC = ["USDNOK", "USDSEK", "EURNOK", "EURSEK"]
EM = ["USDMXN", "USDZAR", "USDPLN", "USDHUF", "USDCNH", "USDTRY"]
METAL = ["XAUUSD", "XAGUSD"]

H_TOKYO = list(range(0, 7))
H_LON = list(range(7, 12))
H_OVL = list(range(12, 17))
H_NYPM = list(range(17, 21))
H_ROLL = [21, 22]
H_EVENT = [12, 13, 14]
H_FOMC = [18, 19, 20]
H_FIX = [15, 16]
H_ALL = list(range(24))

# Measured majors-basket return std (bps) by holding horizon in minutes.
V = {5: 4.4, 15: 6.8, 30: 9.1, 60: 12.5, 120: 17.5, 240: 24.5, 480: 34.3, 1440: 57.9}

SPECS = [
# ---------------------------------------------------------------- F1 event-time
dict(id=1, slot="60", name="Scheduled-news straddle", fam="F1",
 mech="Dealers withdraw depth in the seconds before a scheduled US print, so the book is thinnest exactly when the shock lands. The repricing therefore overshoots fundamentals: each unit of flow has outsized impact and stop/margin liquidations extend the initial move. A taker entering on a stop just outside the pre-release range participates in the cascade without needing to predict direction. The other side is pre-positioned traders being stopped out and dealers dumping inventory. It is not arbitraged because it is a liquidity phenomenon, not a mispricing, and capturing it means bearing gap risk at the worst possible execution moment.",
 rule="On each CPI/NFP/FOMC release date, at T-2min record the high/low of [T-30min, T-2min]. Place an OCO stop-entry buy at high+0.5*range and sell at low-0.5*range, live over [T, T+15min]. Bracket the fill: stop 1.0x range, target 2.0x range, time-exit T+90min. One unit per pair per event.",
 T=100, edge=2.0, vol=30.0, pairs=MAJ6, hours=WD(H_EVENT), legs=1,
 edge_src="First principles. The jump is essentially complete within 60s (Andersen-Bollerslev-Diebold-Vega 2003), so a stop entry is filled after the repricing; only residual cascade is capturable. 2bps is ~20% of the measured 9-14bps mean 5min move.",
 vol_src="Measured: 45-180min post-event std averages 30bps across CPI/NFP/FOMC on majors.",
 falsifier="Triggered trades show no positive expectancy beyond entry slippage, i.e. the post-trigger path is a martingale once the stop-entry fill price is used rather than the pre-release mid.",
 spurious="Survivorship in the trigger rule: only events with large moves trigger, so a naive average over triggered trades conditions on the move already having happened. Using the pre-release mid instead of the actual stop fill would manufacture the entire edge.",
 kill="Net-of-cost expectancy per triggered trade below zero, or >60% of P&L from fewer than 5 events."),

dict(id=2, slot="NOVEL", name="Post-release drift (5-45min)", fam="F1",
 mech="Macro information is impounded in stages: the headline moves price instantly, but the cross-sectional implications are worked out over minutes as different participant types update. Evans-Lyons show order flow keeps transmitting news information after the print. If so, the sign of the release-minute move predicts continued drift over the following half hour. The other side is slower participants rebalancing. It survives arbitrage only to the extent the residual is small relative to execution risk.",
 rule="At T+5min compute r0 = sign(close[T+5] - close[T-1]). Enter in the direction of r0 at T+5, exit at T+45. No stop. One unit per pair per event, CPI/NFP/FOMC.",
 T=180, edge=1.5, vol=22.0, pairs=MAJ6, hours=WD(H_EVENT), legs=1,
 edge_src="Literature-anchored: exploitable post-announcement drift in FX is a small fraction of the initial jump. 1.5bps is ~15% of the measured ~10bps mean 0-5min move.",
 vol_src="Measured: 5-45min post-release std averages 22bps across the three events on majors.",
 falsifier="Regressing the 5-45min return on the 0-5min return across events yields a slope indistinguishable from zero.",
 spurious="Only ~30 events/year, so a handful of large releases dominate; an apparent drift is easily 3-4 observations. Also, a stale quote at T+5 in thin conditions creates artificial autocorrelation.",
 kill="Slope insignificant, or the effect concentrated in one event type only after being proposed for all three."),

dict(id=3, slot="NOVEL", name="Post-release overreaction reversal (45-180min)", fam="F1",
 mech="The headline number is a noisy summary; the detail (core vs headline composition, revisions, participation) is digested over the following hours and frequently qualifies the headline. If the initial jump overshoots the considered interpretation, price partially retraces. The other side is fast momentum traders exiting. This is the opposite sign to spec 2 at a longer horizon; both cannot be right at the same horizon, and proposing both at different horizons is deliberate, not hedging.",
 rule="At T+45min compute r1 = sign(close[T+45] - close[T-1]). Enter AGAINST r1 at T+45, exit at T+180min or session end, whichever first. One unit per pair per event.",
 T=180, edge=2.0, vol=32.0, pairs=MAJ6, hours=WD(H_EVENT), legs=1,
 edge_src="First principles: partial retracement of an overshoot. 2bps is ~20% of the measured 0-5min jump, an upper bound on plausible mean reversal.",
 vol_src="Measured: 45-180min post-event std averages 32bps on majors.",
 falsifier="No negative relation between the 0-45min move and the 45-180min move across events.",
 spurious="Mean reversion appears mechanically if the entry uses a bid/ask-crossed print at a volatile moment. Bar-close sampling at T+45 in a high-vol window embeds bid-ask bounce.",
 kill="Reversal coefficient insignificant, or a positive-drift result appears instead, which would falsify this and belong to spec 2."),

dict(id=4, slot="NOVEL", name="Pre-FOMC dollar drift", fam="F1",
 mech="Lucca-Moench (2015) document large pre-FOMC excess returns in equities, attributed to resolution of policy uncertainty being compensated in advance. The FX analog is a systematic risk-premium tilt in the dollar over the 24h before the statement: if the pre-FOMC period is a risk-on window, the dollar as funding/safe-haven should weaken. The other side is participants unwilling to hold policy risk into the announcement.",
 rule="Short USD (long the non-USD leg) at 18:00 UTC on the day before each FOMC statement day; exit at 17:45 UTC on statement day, before the 18:00/19:00 release. FOMC dates 2013+ only. Equal unit per pair.",
 T=48, edge=6.0, vol=57.9, pairs=MAJ6, hours=WD(H_NYPM), legs=1,
 edge_src="Lucca-Moench report ~49bp equity excess return pre-FOMC; the FX transmission is a fraction of that. 6bps over 24h is a generous read of the dollar analog.",
 vol_src="Measured: 1440min majors-basket std 57.9bps.",
 falsifier="Mean pre-FOMC dollar return indistinguishable from the unconditional mean 24h dollar return.",
 spurious="Only ~8 events/year from 2013 gives ~105 observations total across pairs, and the pairs are ~0.8 correlated so the effective N is closer to 13 independent events. A t-stat computed on 105 would be badly overstated.",
 kill="Effective-N-adjusted t below 2, or the sign driven by 2013-2015 taper-era observations alone."),

dict(id=5, slot="NOVEL", name="Pre-release range fade", fam="F1",
 mech="In the hour before a scheduled release, informed participants stop trading directionally and dealers quote defensively. Price movement in that window is therefore disproportionately uninformed inventory noise, which should revert by the release rather than persist. The other side is small uninformed flow that has to trade. It is not arbitraged away because the window is short and the reversion is small relative to the event risk that follows it.",
 rule="At T-60min record the mid m0. At T-10min, if close deviates from m0 by more than 0.75x the trailing 20-day std of the same 50min window, enter against the deviation; exit at T-1min. Flat into every release. One unit per pair per event.",
 T=180, edge=1.5, vol=10.9, pairs=MAJ6, hours=WD([11, 12, 13]), legs=1,
 edge_src="First principles: fade of uninformed drift. 1.5bps is ~14% of the measured 10.9bps pre-window std, at the optimistic end for noise reversion.",
 vol_src="Measured: 60min pre-release std 10.9bps (majors, excluding one NZDUSD outlier window).",
 falsifier="Pre-release deviations show no negative autocorrelation into the release relative to matched non-event days at the same clock time.",
 spurious="Bid-ask bounce produces spurious reversion at any horizon; the effect must survive using mid quotes and a one-minute execution lag.",
 kill="No reversion versus the matched non-event control, or the effect vanishes with a 1min execution lag."),

dict(id=6, slot="NOVEL", name="Event-day cross-sectional dollar beta", fam="F1",
 mech="A US macro surprise is close to a pure common dollar shock. Pairs load on that shock with stable, heterogeneous betas (AUD and NZD high, CHF and JPY lower and sometimes sign-flipped by safe-haven demand). Trading the high-beta pair against the low-beta pair isolates the dollar factor and cancels idiosyncratic noise, cutting the denominator. The other side is single-pair traders who bear the idiosyncratic component.",
 rule="Estimate each pair's beta to the equal-weight dollar index on a trailing 60 event windows (0-45min), refit annually. On each release, at T+5min go long the top-beta pair and short the bottom-beta pair, sized to equal dollar notional, in the direction of the T+5 dollar-index move. Exit T+45min.",
 T=90, edge=2.5, vol=14.0, pairs=["AUDUSD", "USDCHF"], hours=WD(H_EVENT), legs=2,
 edge_src="First principles: same drift premise as spec 2 but on a lower-noise construct; 2.5bps assumes the spread carries a somewhat larger share of the drift than a single pair.",
 vol_src="Measured 5-45min single-pair std 22bps, reduced to ~14bps for a beta-matched spread at typical 0.7 cross-correlation.",
 falsifier="Betas are unstable out of sample, or the spread shows no drift while single pairs do.",
 spurious="Beta estimated on the same windows used for the test is lookahead; the annual refit must be strictly prior-data-only. Ranking on trailing beta also selects the noisiest pair.",
 kill="Beta rank correlation between adjacent years below 0.3, or two-leg cost exceeds the gross edge."),

# ------------------------------------------------- F2 session / time-of-day
dict(id=7, slot="NOVEL", name="Ranaldo local-hour segmentation", fam="F2",
 mech="Ranaldo (2009) documents that a currency depreciates during its own domestic trading hours and appreciates during foreign hours, a robust intraday pattern driven by order-flow segmentation: domestic institutions are net sellers of domestic currency during their own working day (import settlement, hedging, payroll), and that flow is absorbed by dealers who must be compensated. The other side is dealers earning the spread and the intraday reversal. It persists because the flow is non-discretionary and recurs daily.",
 rule="For each of EURUSD, GBPUSD, USDJPY: short the domestic currency during its local session hours (EUR 07-15 UTC, GBP 07-16 UTC, JPY 00-07 UTC) and hold flat otherwise. One entry and one exit per pair per day at fixed clock times.",
 T=252 * 3, edge=1.6, vol=25.0, pairs=["EURUSD", "GBPUSD", "USDJPY"], hours=WD([7, 8, 9, 10, 11, 12, 13, 14, 15]), legs=1,
 edge_src="Ranaldo (2009) reports intraday segmentation effects of a few bps per day on majors. 1.6bps/day is a mid-range read of the published magnitude.",
 vol_src="Measured: ~8h holding horizon, majors-basket std 34.3bps at 480min, scaled down to 25bps for the lower-vol subset traded.",
 falsifier="The local-hour return is not reliably negative for the domestic currency once the sample is split by decade.",
 spurious="The effect is old (published 2009 on 1993-2005 data) and is exactly the kind of pattern algorithmic execution has since competed away. A positive result on 2011-2026 must be checked for concentration in the early years.",
 kill="First-half vs second-half sample sign flip, or the effect surviving only before 2015."),

dict(id=8, slot="10", name="Asian range fade", fam="F2",
 mech="The Tokyo session has the thinnest G10 depth of the three majors sessions, so the same order size moves price further than it would in London. Moves established on Asian liquidity are therefore disproportionately impact rather than information, and are partially retraced when London depth arrives. The other side is Asian-hours participants who must transact locally. It persists because the retracement is small relative to the cost of holding the position into London.",
 rule="Record the Tokyo range [00:00, 06:00 UTC]. At 07:00 UTC, if price is above the Tokyo high, sell; if below the low, buy. Target the Tokyo range midpoint, stop 1.0x range beyond entry, time-exit 12:00 UTC. One unit per pair per day.",
 T=200, edge=2.0, vol=17.5, pairs=["USDJPY", "AUDJPY"], hours=WD([7, 8]), legs=1,
 edge_src="First principles: partial retracement of impact-driven Asian moves. 2.5bps is ~14% of the 120min majors std.",
 vol_src="Measured: 120min majors-basket std 17.5bps.",
 falsifier="Breaks of the Tokyo range at the London open continue rather than retrace, on average.",
 spurious="Range-break rules condition on volatility, so the sample is drawn from high-vol days where mean reversion and momentum are both easier to find by chance. A matched-vol control is required.",
 kill="No retracement versus a matched-volatility control, or expectancy negative on JPY crosses after the measured cost."),

dict(id=9, slot="13", name="End-of-day reversal", fam="F2",
 mech="The 21:00-22:00 UTC rollover concentrates non-discretionary flow: daily settlement, swap rolls, and risk-limit squaring, all price-insensitive. That flow pushes price away from fair value in the last hour and is reversed once the new session's liquidity arrives. The other side is desks that must flatten before their book rolls. It persists because the reversal window has the widest spreads of the week, which is itself the barrier to arbitrage.",
 rule="Measure the 20:00-21:00 UTC return. At 22:00 UTC enter against it if its magnitude exceeds 0.5x the trailing 20-day std of that hour. Exit at 01:00 UTC. One unit per pair per day.",
 T=252 * 3, edge=2.0, vol=12.5, pairs=["EURUSD", "USDJPY", "GBPUSD"], hours=WD(H_ROLL), legs=1,
 edge_src="First principles: reversal of price-insensitive settlement flow. 2bps is ~16% of the 60min majors std.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="The 20:00-21:00 return shows no negative autocorrelation with the subsequent overnight return.",
 spurious="This window carries among the widest measured weekday spreads (EURUSD 3.50x at 21:00 and 3.94x at 22:00 UTC). Any mid-quote-based result will look profitable and be untradeable; only executable prices settle it.",
 kill="Cost-adjusted expectancy negative, which the measured rollover spread makes the likely outcome."),

dict(id=10, slot="21", name="NY continuation", fam="F2",
 mech="The London close at 16:00-17:00 UTC removes roughly half of G10 liquidity while the US session continues. A directional move already underway meets a thinner book after the London handover, so the same residual flow produces larger price change, extending the move. The other side is the departing London liquidity. It persists because it requires holding into the thinning NY afternoon.",
 rule="Compute the 12:00-16:00 UTC return. At 17:00 UTC enter in the same direction if magnitude exceeds 0.75x the trailing 20-day std of that window. Exit 20:00 UTC. One unit per pair per day.",
 T=340, edge=2.0, vol=17.5, pairs=MAJ4[:3], hours=WD(H_NYPM), legs=1,
 edge_src="First principles: continuation on thinning depth. 2bps is ~11% of the 120min majors std.",
 vol_src="Measured: 120min majors-basket std 17.5bps.",
 falsifier="No positive relation between the overlap-session return and the NY-afternoon return.",
 spurious="Momentum and reversal specs on adjacent windows (this and spec 9) can both appear to work on the same data through window-slicing. Only one sign can be structurally true at a given horizon.",
 kill="Relation insignificant, or opposite in sign to spec 9's premise in a way that is not reconcilable."),

dict(id=11, slot="22", name="Tokyo JPY-cross mean reversion", fam="F2",
 mech="JPY crosses in Tokyo hours are dominated by domestic institutional flow (exporter hedging, Gotobi settlement on days divisible by five) which is calendar-driven and price-insensitive. Price-insensitive flow creates temporary displacement that reverts once it completes. The other side is Japanese corporates who must settle regardless of level. It persists because the displacement is small and the Tokyo spread is wider than London's.",
 rule="On Gotobi days (5th, 10th, 15th, 20th, 25th, last business day), measure the 00:00-02:00 UTC return; enter against it at 02:00 UTC if magnitude exceeds 0.5x the trailing 20-day std of that window; exit 06:00 UTC.",
 T=108, edge=2.2, vol=17.5, pairs=JPYX[:3], hours=WD([2, 3, 4, 5]), legs=1,
 edge_src="First principles from the documented Gotobi fixing convention; 3bps is ~17% of the 240min std, reflecting a concentrated known flow.",
 vol_src="Measured: 120-240min majors std 17.5-24.5bps; Tokyo hours run ~0.74x the all-hours level, so 17.5bps.",
 falsifier="Gotobi days show no different intraday reversion profile from matched non-Gotobi days.",
 spurious="Gotobi is a well-known retail talking point; if it were this easy it would be gone. The control against non-Gotobi days is the whole test, and without it any Tokyo-hours reversion would be misattributed.",
 kill="No Gotobi-vs-control difference, in which case this collapses into generic Tokyo reversion and is not a separate mechanism."),

dict(id=12, slot="25", name="Session-transition volatility expansion", fam="F2",
 mech="At each session handover (Tokyo->London 07:00, London->NY 12:00, London close 16:00) the participant mix changes abruptly and the new session's participants reprice against the previous session's close. That produces a systematic burst of directional movement in the first 30 minutes of each handover. Trading the direction of the first minutes of the handover captures the repricing. The other side is stale quotes from the departing session.",
 rule="At each of 07:00, 12:00, 17:00 UTC, measure the first 10min return; enter in that direction at +10min; exit at +40min. Stop 1.5x the 10min move. One unit per pair per transition.",
 T=252 * 3 * 3, edge=1.2, vol=9.1, pairs=MAJ4[:3], hours=WD([7, 12, 17]), legs=1,
 edge_src="First principles: short-horizon continuation on regime handover. 1.2bps is ~13% of the 30min majors std.",
 vol_src="Measured: 30min majors-basket std 9.1bps.",
 falsifier="First-10min direction does not predict the next 30min at session handovers any better than at arbitrary clock times.",
 spurious="With ~2270 trades/year the standard error is small, so a tiny bias in bar construction (e.g. the first bar of a session including a stale print) can dominate the result.",
 kill="No excess predictability versus arbitrary-clock-time control, or sensitivity to the first-bar construction."),

dict(id=13, slot="56", name="EM local-open effect", fam="F2",
 mech="EM currencies trade primarily in their own onshore hours, when local banks and the central bank are active. The transition from offshore (thin, G10-hours) to onshore pricing produces a systematic repricing at the local open as onshore participants reconcile the overnight offshore drift with local conditions. The other side is offshore holders. It persists because EM spreads are wide enough to deter arbitrage.",
 rule="For USDMXN and USDZAR, measure the offshore overnight return to the local open (13:00 UTC for MXN, 06:00 UTC for ZAR); enter against it at the local open if magnitude exceeds 1.0x the trailing 20-day std; exit 4h later.",
 T=200, edge=6.0, vol=31.0, pairs=["USDMXN", "USDZAR"], hours=WD([6, 13]), legs=1,
 edge_src="First principles: onshore-offshore reconciliation. 6bps is ~19% of the 240min EM std, justified by the much wider EM spread barrier.",
 vol_src="Measured: 240min std 31.7bps (USDMXN) and 40.0bps (USDZAR); 31bps is the conservative blend.",
 falsifier="No reconciliation effect at the local open beyond generic reversion at any hour.",
 spurious="EM pairs carry large interest differentials; a spec that is systematically long the high-yielder will look profitable from carry alone and must be decomposed spot-vs-carry.",
 kill="Effect absent after removing carry accrual, or measured cost (USDMXN 4.32bps, USDZAR 5.54bps round trip) exceeds gross edge."),

dict(id=14, slot="57", name="NOKSEK microstructure reversion", fam="F2",
 mech="NOK and SEK are the least liquid G10 currencies and share a near-identical macro driver (small open European economies, correlated rate cycles). Idiosyncratic order flow in one leg displaces it relative to the other, and because both are thin the displacement is larger and slower to correct than in majors. The other side is a dealer absorbing a block in one currency. It persists because the pair is thin enough that arbitrage capital is capacity-constrained.",
 rule="Form the NOKSEK cross from USDNOK and USDSEK. Compute a 240min z-score of the log cross against its 20-day mean; enter against a |z|>2.0 deviation; exit on z crossing 0.5 or after 24h.",
 T=150, edge=5.0, vol=30.0, pairs=["USDNOK", "USDSEK"], hours=WD(H_LON + H_OVL), legs=2,
 edge_src="First principles: thin-market displacement reversion. 9bps is ~30% of the 240min Nordic std, reflecting genuinely slow correction in a capacity-constrained pair.",
 vol_src="Measured: 240min std 33.0bps (USDNOK), 29.2bps (USDSEK); the cross is less volatile than either leg, ~30bps.",
 falsifier="The synthetic cross shows no mean reversion at the 240min horizon after costs.",
 spurious="This is a two-leg trade in the two most expensive G10 pairs on the measured surface (3.43 and 3.96bps round trip each). A mid-quote backtest will show a large edge that the 7.4bps two-leg cost erases entirely.",
 kill="Two-leg cost-adjusted if-true Sharpe below the bar, which the screen already indicates."),

dict(id=15, slot="59", name="Hour-of-week volatility surface conditioning", fam="F2",
 mech="Volatility has a stable, strongly periodic hour-of-week shape driven by session overlap and settlement conventions. A signal calibrated on unconditional volatility is therefore mis-scaled at every hour: it over-trades in quiet hours and under-trades in active ones. Conditioning entry thresholds on the hour-specific volatility norm should raise the information ratio of any reversion signal without changing its mechanism. The other side is participants using unconditional thresholds.",
 rule="Take a fixed 60min z-reversion signal (enter at |z|>2 vs trailing 20-period mean, exit on z<0.5 or 4h). Compute z using the hour-of-week-specific volatility norm from a trailing 52-week window rather than an unconditional one. Trade only hours 07-20 UTC.",
 T=650, edge=1.8, vol=12.5, pairs=MAJ4, hours=WD(H_LON + H_OVL + H_NYPM), legs=1,
 edge_src="First principles: correct scaling of an existing signal. 1.8bps is ~14% of the 60min majors std, assuming conditioning adds a modest amount to a baseline reversion edge.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="Hour-conditioned thresholds produce no higher information ratio than unconditional ones on the same signal.",
 spurious="This is a refinement of a signal family, not an independent mechanism; if the base reversion signal has no edge, conditioning cannot create one. Presenting it as a new mechanism would be double-counting.",
 kill="No improvement over the unconditional baseline, or the baseline itself has no edge."),

dict(id=16, slot="58", name="Volatility spillover network", fam="F2",
 mech="A volatility shock in one currency propagates to correlated currencies with a short lag because dealers hedge correlated inventory and risk models update across a book. The pair that has not yet moved is therefore temporarily mispriced relative to the one that has. The other side is dealers rebalancing. It persists only at horizons short enough that the propagation is incomplete.",
 rule="Every 15min compute realized 60min vol for the G10 set. When one pair's vol z-score exceeds 2.5 and a historically >0.7-correlated partner's is below 1.0, enter the partner in the direction of the leader's 15min return; exit after 60min.",
 T=252 * 4, edge=1.5, vol=12.5, pairs=G10[:6], hours=WD(H_LON + H_OVL), legs=1,
 edge_src="First principles: incomplete cross-pair propagation. 1.5bps is ~12% of the 60min majors std.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="The lagging pair's subsequent return is unrelated to the leader's move once contemporaneous correlation is removed.",
 spurious="Correlated pairs share the USD leg, so any 'spillover' is largely a mechanical dollar move rather than propagation. The test must be run on the non-USD residual or it measures nothing.",
 kill="Effect disappears after removing the common dollar factor."),

dict(id=17, slot="14", name="Weekend gap fade", fam="F2",
 mech="The Friday close to Sunday open gap reflects weekend news plus a thin-liquidity opening print. The opening print in particular is set on almost no depth, so it overshoots the level at which weekday liquidity clears, and retraces during the first Asian hours. The other side is participants forced to trade at the Sunday open. It persists because the Sunday-open spread is the widest of the week.",
 rule="At the Sunday 22:00 UTC open, measure the gap versus the Friday 21:00 UTC close. If |gap| > 0.5x the trailing 20-week gap std, enter against it; exit at Monday 07:00 UTC.",
 T=60, edge=2.5, vol=17.5, pairs=MAJ4[:3], hours=[6 * 24 + 22, 6 * 24 + 23], legs=1,
 edge_src="First principles: fade of a thin opening print. 4bps is ~23% of the 120min majors std, generous for a gap-fade.",
 vol_src="Measured: 120min majors-basket std 17.5bps.",
 falsifier="Weekend gaps are not systematically retraced during the first Asian session.",
 spurious="A gap-fade backtest on mid quotes ignores that the Sunday reopening is among the most expensive blocks of the week: the surface DOES measure these hours and charges EURUSD 3.84x its average multiplier at 22:00 UTC Sunday, roughly double the all-in London-hours cost. With only ~60 trades a year there is also no route to statistical comfort.",
 kill="Cost-adjusted expectancy negative, or fewer than 40 effectively independent gaps in the sample."),

# --------------------------------------------------- F3 benchmark fixing flow
dict(id=18, slot="32", name="Month-end fix flow", fam="F3",
 mech="Melvin-Prins document that month-end FX flow is driven by equity-portfolio hedge rebalancing: after a month in which foreign equities outperform, hedgers must sell foreign currency to restore hedge ratios, and this flow is price-insensitive, predictable in sign from the month's equity returns, and concentrated into the 16:00 London WMR fix. The other side is dealers absorbing a known imbalance. It persists because the hedgers are mandate-driven and cannot delay.",
 rule="On the last business day of each month, at 14:00 UTC take the sign of the month's MSCI-proxy relative equity return (use SPY vs a foreign equity ETF as the proxy; if unavailable use the month's cumulative pair return as the rebalancing proxy). Enter in the direction implied by hedge rebalancing; exit at 16:05 UTC just after the fix window.",
 T=12 * 6, edge=6.0, vol=20.0, pairs=MAJ6, hours=WD(H_FIX), legs=1,
 edge_src="Melvin-Prins (2015) document month-end fix effects of order 10-20bps on major pairs conditional on the rebalancing signal. 6bps is a conservative read after accounting for the signal proxy being imperfect.",
 vol_src="Measured: ~2h holding window, majors-basket 120min std 17.5bps, raised to 20bps for the elevated fix window.",
 falsifier="Month-end fix returns show no relation to the prior month's relative equity performance.",
 spurious="Only 12 events/year: with 6 correlated pairs the effective N is ~12/year, so 15 years gives ~180 effectively-correlated observations but far fewer independent ones. Also, the equity-return proxy is the weakest link and could be fit after the fact.",
 kill="Relation to the equity proxy insignificant, or >50% of P&L from fewer than 8 month-ends."),

dict(id=19, slot="23", name="WMR 16:00 fix impact and reversal", fam="F3",
 mech="The WMR benchmark is computed over a short window around 16:00 London, and a large share of passive and corporate flow is required to execute at that benchmark. Concentrated price-insensitive flow moves price into the window and the impact partially reverses afterwards once the flow stops. Since the 2013 benchmark reform widened the window to 5 minutes, the impact is smaller but the reversal mechanism is unchanged. The other side is dealers who pre-hedge the fix.",
 rule="Measure the return over the fix window (15:45-16:05 UTC, using 16:00 London in local time so the UTC hour shifts with BST). If it exceeds 0.75x its trailing 60-day std, enter against it at 16:05 UTC and exit at 17:05 UTC.",
 T=400, edge=1.8, vol=12.5, pairs=MAJ4, hours=WD(H_FIX), legs=1,
 edge_src="Evans (2018) and the benchmark-reform literature document fix-window impact with partial post-fix reversal; magnitude fell materially after the 2013 reform. 2.5bps is a post-reform estimate.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="No negative autocorrelation between the fix-window return and the following hour.",
 spurious="The pre-2013 and post-2013 regimes differ by construction; pooling them would show a strong effect driven entirely by the pre-reform era. The spec must be evaluated post-2013 only.",
 kill="Effect present only pre-2015, or insignificant on the post-reform subsample which is the only economically live one."),

dict(id=20, slot="24", name="Friday position-squaring fade", fam="F3",
 mech="Leveraged participants reduce risk into the weekend because weekend gap risk cannot be hedged. That squaring is price-insensitive and concentrated in the Friday NY afternoon, displacing price against the prevailing week's position. Once the squaring completes the displacement reverts. The other side is dealers absorbing the unwind. It persists because holding the reversion means carrying weekend gap risk.",
 rule="Measure the Friday 12:00-19:00 UTC return. If it opposes the sign of the Monday-Thursday cumulative return and exceeds 0.5x its trailing 20-week std, enter in the direction of the week's move at 19:00 UTC Friday; exit at Monday 08:00 UTC.",
 T=52 * 3, edge=5.0, vol=57.9, pairs=MAJ4[:3], hours=[4 * 24 + h for h in [17, 18, 19]], legs=1,
 edge_src="First principles: reversion of an identifiable squaring flow. 5bps is ~9% of the weekend-spanning std.",
 vol_src="Measured: 1440min majors-basket std 57.9bps, the closest available proxy for a Friday-to-Monday hold.",
 falsifier="Friday-afternoon counter-trend moves are not systematically reversed by Monday.",
 spurious="Holding over the weekend means the result is dominated by weekend gap risk, a fat-tailed variable. A good Sharpe here can coexist with catastrophic tail exposure that Sharpe does not price.",
 kill="Positive mean but negative skew such that the worst 3 weekends erase the cumulative P&L."),

dict(id=21, slot="NOVEL", name="Quarter-end fix amplification", fam="F3",
 mech="Quarter-end concentrates the month-end rebalancing mechanism of spec 18 with additional balance-sheet and reporting-driven flow: banks reduce balance sheet for regulatory reporting dates, which withdraws liquidity precisely when rebalancing flow peaks. The same predictable flow therefore meets a thinner book and produces larger displacement. The other side is a constrained dealer sector. It persists because the constraint is regulatory, not economic.",
 rule="Identical to spec 18 but restricted to the last business day of March, June, September and December, with a 2x position scale and the window extended to 13:00-16:05 UTC.",
 T=4 * 6, edge=12.0, vol=24.5, pairs=MAJ6, hours=WD(H_FIX), legs=1,
 edge_src="First principles plus the balance-sheet literature: quarter-end effects in funding markets are roughly 2x month-end. 12bps is 2x the spec 18 estimate.",
 vol_src="Measured: 240min majors-basket std 24.5bps.",
 falsifier="Quarter-ends show no larger effect than ordinary month-ends.",
 spurious="Only 4 events/year, i.e. ~60 observations across 15 years and 6 correlated pairs -- effectively ~15 independent events. This is the single most overfit-prone spec in the slate and is proposed only because the mechanism is strong.",
 kill="Fewer than 40 independent events available, or the quarter-end effect indistinguishable from the month-end effect, which would make it a duplicate of spec 18 rather than a distinct mechanism."),

# ------------------------------------------- F4 intraday breakout / expansion
dict(id=22, slot="5", name="Breakout-pullback continuation", fam="F4",
 mech="A genuine breakout is followed by a pullback as early entrants take profit, then resumes if the breakout reflected real order-flow imbalance rather than a stop run. Entering on the pullback rather than the break itself filters stop-run false breaks, because a stop run has no residual imbalance to resume the move. The other side is the profit-takers. It persists because waiting for the pullback means missing the moves that never pull back.",
 rule="On 15min bars, mark a breakout when price exceeds the 24-bar high. Wait for a retracement to 0.382 of the breakout leg within 8 bars; enter long there; stop below the breakout base; target 1.618x the leg; time-exit 24 bars.",
 T=250, edge=2.5, vol=24.5, pairs=MAJ4[:3], hours=WD(H_LON + H_OVL), legs=1,
 edge_src="First principles: conditional continuation after a filter. 3bps is ~12% of the 240min majors std.",
 vol_src="Measured: 240min majors-basket std 24.5bps.",
 falsifier="Pullback entries show no better expectancy than immediate breakout entries.",
 spurious="Fibonacci retracement levels have no mechanism; 0.382 is arbitrary and any of a dozen levels could be chosen post hoc. The level is fixed here precisely to prevent that, and a result that depends on the exact level is a tell.",
 kill="Result sensitive to the retracement level, or no improvement over the unfiltered breakout."),

dict(id=23, slot="2", name="Donchian channel breakout", fam="F4",
 mech="Central banks smooth exchange-rate adjustment and corporates hedge gradually, so information is impounded slowly and price trends. A channel break marks the point at which accumulated information has overcome the prevailing range, and the residual adjustment continues. The other side is hedgers transacting on a schedule. It persists because trend-following requires tolerating long drawdowns that most capital cannot hold.",
 rule="Daily bars. Enter long on a close above the 55-day high, short below the 55-day low. Exit on a close through the 20-day opposite extreme. ATR(20)-based sizing at a fixed 10% annualized vol target per pair.",
 T=40, edge=25.0, vol=260.0, pairs=G10, hours=WD(H_OVL), legs=1,
 edge_src="Derived from literature: published FX trend-following net Sharpe is 0.3-0.6 (Menkhoff-Sarno-Schmeling-Schrimpf 2012). Backing out per-trade edge at T=40 and a ~20-day hold gives ~25bps gross.",
 vol_src="Measured: 1440min std 57.9bps scaled to a ~20-day hold -> ~260bps.",
 falsifier="No positive relation between channel breaks and subsequent returns in the modern sample.",
 spurious="Trend-following results are dominated by a few large moves; a single 2015 CHF or 2022 JPY episode can carry the whole record and will not recur on demand.",
 kill="Removing the single best quarter turns cumulative P&L negative."),

dict(id=24, slot="7", name="Multi-timeframe momentum alignment", fam="F4",
 mech="Momentum measured at a single horizon is noisy; requiring agreement across horizons filters transient noise from persistent order-flow imbalance. Alignment across 1h, 4h and daily should therefore select the subset of moves driven by real accumulation rather than by a single participant. The other side is short-horizon noise traders. It persists because the aligned subset is small and the waiting cost is high.",
 rule="Enter long when the 1h, 4h and daily returns are all positive and the daily is above its 20-day mean; short on the mirror. Exit when any horizon flips. Evaluated on 1h bars, one position per pair.",
 T=150, edge=3.5, vol=24.5, pairs=MAJ4, hours=WD(H_LON + H_OVL + H_NYPM), legs=1,
 edge_src="First principles: filtered momentum. 3.5bps is ~14% of the 240min majors std.",
 vol_src="Measured: 240min majors-basket std 24.5bps.",
 falsifier="Multi-horizon agreement adds no expectancy over the single best horizon alone.",
 spurious="Three horizons is a choice among many; requiring agreement is a free parameter that can be tuned until something passes. Horizons are fixed here at conventional values to prevent that.",
 kill="No improvement over single-horizon momentum, making this a parameter variation rather than a mechanism."),

dict(id=25, slot="26", name="NR7 range-compression squeeze", fam="F4",
 mech="Volatility is strongly autocorrelated and mean-reverting in level: an unusually narrow range signals a temporary contraction in the arrival of information and in dealer risk appetite, which is followed by expansion. The direction of the expansion is set by whichever side of the compressed range breaks first, because the compressed range concentrates resting stop orders on both sides. The other side is those stops. It persists because the direction is genuinely unpredictable ex ante.",
 rule="Daily bars. When today's range is the narrowest of the last 7 days, place an OCO bracket at the day's high and low for the next session; stop at the opposite extreme; target 2x the compressed range; time-exit at the following day's close.",
 T=90, edge=6.0, vol=57.9, pairs=MAJ4, hours=WD(H_LON + H_OVL), legs=1,
 edge_src="First principles: volatility expansion after compression. 8bps is ~14% of the daily majors std.",
 vol_src="Measured: 1440min majors-basket std 57.9bps.",
 falsifier="Post-NR7 sessions show no larger realized range than matched ordinary sessions.",
 spurious="Range expansion after compression is near-certain by mean reversion in volatility, but that does not make the DIRECTIONAL bracket profitable. Confusing 'range expands' with 'the bracket makes money' is the trap here: a symmetric bracket in an expanding but directionless market loses on both sides.",
 kill="Range expands but bracket expectancy is negative, which would confirm the vol/direction confusion."),

dict(id=26, slot="28", name="ATR-regime switch", fam="F4",
 mech="Trend-following and mean-reversion work in different volatility regimes: in high-volatility regimes moves are information-driven and persist, in low-volatility regimes moves are inventory noise and revert. A single rule applied across both regimes averages two opposite effects toward zero. Switching the rule on a volatility state variable should recover both. The other side differs by regime, which is the point.",
 rule="Compute ATR(20)/close on daily bars and its 250-day percentile. Above the 70th percentile run a 20/50 MA crossover trend rule; below the 30th run a 2-std Bollinger fade on daily closes; between, stay flat. One position per pair.",
 T=60, edge=22.0, vol=180.0, pairs=G10, hours=WD(H_OVL), legs=1,
 edge_src="Derived from literature as in spec 23; regime switching claims to lift a 0.3-0.6 Sharpe trend rule modestly, so per-trade gross edge ~22bps at a ~12-day mean hold.",
 vol_src="Measured: 1440min std 57.9bps scaled to a ~10-12 day mean hold -> ~180bps.",
 falsifier="Conditional Sharpe in the two regimes is not materially different from unconditional.",
 spurious="The percentile thresholds (70/30) and the two sub-rules are four free parameters; this family is where regime-switching results are usually manufactured. Fixed here, but the degrees of freedom remain a live concern.",
 kill="Either sub-rule alone matches the switched version, meaning the switch adds nothing."),

dict(id=27, slot="1", name="Dual MA with ATR trailing stop", fam="F4",
 mech="Same slow-information-diffusion mechanism as spec 23, but with the exit governed by a volatility-scaled trailing stop rather than an opposite channel break. The exit is the real hypothesis here: trend P&L is dominated by how much of a large move is retained, so a volatility-adaptive trailing exit should retain more than a fixed-horizon or channel exit. The other side is unchanged.",
 rule="Daily bars. Long when MA(20) crosses above MA(60), short on the mirror. Exit on a 3.0x ATR(20) trailing stop from the run-up extreme, or on an opposite cross. Vol-targeted sizing at 10% annualized.",
 T=45, edge=24.0, vol=250.0, pairs=G10, hours=WD(H_OVL), legs=1,
 edge_src="Derived from literature as in spec 23: FX trend net Sharpe 0.3-0.6, backed out at T=45 and a ~18-day hold.",
 vol_src="Measured: 1440min std 57.9bps scaled to an ~18-day hold -> ~250bps.",
 falsifier="The trailing exit does not retain more of large moves than the spec 23 channel exit.",
 spurious="This differs from spec 23 mainly in the exit, so a difference in results between them is as likely to be noise as mechanism. Treating both as independent evidence would double-count one idea.",
 kill="Indistinguishable from spec 23, in which case it is a parameter variation and should not consume a separate trial."),

# ------------------------------------------------- F5 intraday mean reversion
dict(id=28, slot="11", name="Hourly z-score reversion", fam="F5",
 mech="Dealers absorbing a large order accumulate inventory they do not want and must be compensated for holding it; they lay it off over the following hour, and price returns toward the pre-shock level. As a taker we do not earn the spread, only the residual overshoot beyond it, which is the honest and much smaller part of the inventory premium. The other side is the dealer laying off risk. It persists because the compensation is the dealer's, not ours.",
 rule="On 60min bars compute z = (close - MA20)/std20. Enter against |z| > 2.0 at the bar close; exit when |z| < 0.5 or after 6 bars. Trade only 07:00-20:00 UTC. One position per pair.",
 T=655, edge=1.6, vol=12.5, pairs=MAJ4, hours=WD(H_LON + H_OVL + H_NYPM), legs=1,
 edge_src="First principles: taker-side residual of the inventory premium. 1.6bps is ~13% of the 60min majors std, and deliberately below what a maker would earn.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="No negative autocorrelation at the 1-6 hour horizon after removing bid-ask bounce.",
 spurious="Bid-ask bounce guarantees measured negative autocorrelation at short horizons in mid-quote data. If the test does not execute at ask-on-buy and bid-on-sell, the entire result is the bounce.",
 kill="Effect vanishes under executable pricing, or net edge below the 1.5x cost-sensitivity threshold."),

dict(id=29, slot="9", name="RSI(2) intraday fade", fam="F5",
 mech="Same inventory-absorption mechanism as spec 28, but the trigger is a short-lookback oscillator that fires on rapid sequential moves rather than on a level deviation. The distinction is real: a fast 2-period extreme identifies a burst of one-directional flow, while a z-score identifies a sustained displacement. They select different events despite sharing a mechanism.",
 rule="On 15min bars compute RSI(2). Enter long below 5, short above 95, at the bar close. Exit when RSI(2) crosses 50 or after 16 bars. Trade 07:00-20:00 UTC only.",
 T=252 * 8, edge=1.1, vol=9.1, pairs=MAJ4, hours=WD(H_LON + H_OVL + H_NYPM), legs=1,
 edge_src="First principles: same taker-side residual as spec 28 at a shorter horizon. 1.1bps is ~12% of the 30min majors std.",
 vol_src="Measured: 30min majors-basket std 9.1bps.",
 falsifier="RSI(2) extremes show no subsequent reversion beyond the bid-ask bounce.",
 spurious="At ~2000 trades/year the cost term dominates: gross edge 1.1bps against ~0.9bps cost leaves almost nothing, so a small cost misestimate flips the sign. This spec is a cost-model test as much as a signal test.",
 kill="Fails the 1.5x cost-sensitivity gate, which on these numbers is close to certain."),

dict(id=30, slot="8", name="Bollinger band reversion (daily)", fam="F5",
 mech="At the daily horizon, deviations from a 20-day mean reflect either information (which persists) or flow (which reverts). The band width conditions on realized volatility so a 2-std break is a comparable event across regimes. The reversion component is the compensation for providing liquidity to multi-day flow. The other side is a participant executing a large program over days.",
 rule="Daily bars. Enter against a close outside the 20-day 2.0-std Bollinger band; exit on a close back inside the 1.0-std band or after 10 days.",
 T=30, edge=30.0, vol=185.0, pairs=G10, hours=WD(H_OVL), legs=1,
 edge_src="Derived from literature: daily FX reversion strategies report net Sharpe well under 0.5. Backed out at T=30 and a ~10-day hold.",
 vol_src="Measured: 1440min std 57.9bps scaled to a ~10-day hold -> ~185bps.",
 falsifier="No reversion after 2-std daily breaks in the modern sample.",
 spurious="Daily mean reversion in FX is heavily regime-dependent and blows up in trends; a positive average with a catastrophic tail is the classic presentation of this family.",
 kill="Max drawdown exceeding 3x the annualized return, or negative skew concentrated in trending years."),

dict(id=31, slot="NOVEL", name="Rollover-window displacement reversion", fam="F5",
 mech="At 21:00-22:00 UTC the interbank day rolls: swap points are applied, daily risk limits reset, and many venues briefly widen or halt. Flow that must transact in that window is entirely price-insensitive, and the displacement it causes is mechanical rather than informational, so it reverts once normal liquidity resumes in Asia. The other side is desks with no choice about timing. It is not arbitraged because the window has the widest measured spreads of the week.",
 rule="Measure the 21:00-22:00 UTC return. If |return| exceeds 1.5x its trailing 20-day std, enter against it at 23:00 UTC (after the widest hour has passed) and exit at 03:00 UTC.",
 T=252 * 3, edge=3.0, vol=17.5, pairs=["EURUSD", "USDJPY", "AUDUSD"], hours=WD([23]), legs=1,
 edge_src="First principles: reversion of mechanical settlement displacement. 3bps is ~17% of the 120min majors std.",
 vol_src="Measured: 120min majors-basket std 17.5bps.",
 falsifier="Rollover-window moves are not systematically reversed in the subsequent Asian session.",
 spurious="Entering at 23:00 rather than 22:00 is a deliberate cost choice, but the 23:00 hour is still 1.1-2.3x the pair's average spread. A version that entered at 22:00 would look better on mids and be untradeable.",
 kill="Reversion absent, or entry-hour sensitivity such that only the 22:00 entry works."),

# ------------------------------------------- F6 cross-sectional / dollar factor
dict(id=32, slot="54", name="Cross-sectional intraday relative strength", fam="F6",
 mech="Within a trading session, currencies that have outperformed on genuine order-flow imbalance tend to continue relative to those that have not, because institutional execution programs are worked over hours rather than minutes. Ranking cross-sectionally removes the common dollar factor and isolates the currency-specific flow. The other side is the program's counterparty. It persists because the programs are large and slow.",
 rule="At 12:00 UTC rank the G10 set by return since 07:00 UTC. Go long the top 2 and short the bottom 2, equal notional, dollar-neutral. Exit at 20:00 UTC. One rebalance per day.",
 T=252 * 4, edge=3.5, vol=24.5, pairs=G10[:8], hours=WD(H_OVL), legs=4,
 edge_src="First principles: intraday continuation of institutional execution. 3.5bps is ~14% of the 240min majors std.",
 vol_src="Measured: 240min majors-basket std 24.5bps; the dollar-neutral basket is comparable after netting.",
 falsifier="Intraday relative-strength rank has no predictive power for the remainder of the session.",
 spurious="A 4-leg construction pays four round-trip costs against a single spread's edge; the screen's single-leg cost understates the true charge fourfold. This is stated explicitly below.",
 kill="Four-leg cost-adjusted if-true Sharpe below the bar."),

dict(id=33, slot="4", name="Cross-sectional momentum (dollar-neutral re-form)", fam="F6",
 mech="Re-form of a naive-only slot. The naive version ranked pairs by raw return, which conflates the common dollar factor with currency-specific momentum: in a dollar rally every USD pair ranks together and the portfolio is a disguised dollar bet. The re-form ranks CURRENCIES by their average return against all others, so the dollar is a rankable currency rather than an embedded factor. That is a different functional form, not a retuned parameter.",
 rule="Monthly. Build the 10x10 currency return matrix from G10 crosses over the trailing 3 months. Rank each currency by mean return against all others. Long the top 3, short the bottom 3, equal weight, held one month, rebalanced month-end.",
 T=12 * 6, edge=45.0, vol=430.0, pairs=G10, hours=WD(H_OVL), legs=6,
 edge_src="Derived from literature: FX cross-sectional momentum net Sharpe ~0.3-0.5 (Menkhoff et al. 2012). Backed out at T=72 and a 1-month hold.",
 vol_src="Measured: 1440min std 57.9bps scaled to a 21-trading-day hold -> ~265bps per leg, ~430bps for a 6-leg portfolio after partial diversification.",
 falsifier="Currency-level momentum has no cross-sectional predictive power once the dollar factor is rankable rather than embedded.",
 spurious="FX momentum has decayed sharply since 2010 in published work; a positive result on 2011-2026 would run against the literature and should be treated as suspect rather than as a discovery.",
 kill="Literature-implied Sharpe below the bar, which the screen confirms -- route to combination."),

dict(id=34, slot="40", name="Correlation-breakdown reversion", fam="F6",
 mech="Currency pairs sharing macro drivers maintain stable correlations. A sudden breakdown usually reflects a one-sided flow in one leg rather than a genuine divergence in fundamentals, so the relationship re-establishes. The other side is whoever needed to move that one leg. It persists because identifying a true regime change from a temporary flow requires holding through ambiguity.",
 rule="For the AUDUSD/NZDUSD and EURUSD/USDCHF pairs, compute the 60-day rolling correlation and the 20-day spread z-score. When correlation stays above 0.7 but |spread z| > 2.0, enter against the spread; exit on |z| < 0.5 or 15 days.",
 T=25, edge=55.0, vol=230.0, pairs=["AUDUSD", "NZDUSD"], hours=WD(H_OVL), legs=2,
 edge_src="First principles: convergence of a temporarily displaced stable relationship. 55bps is ~24% of the 15-day spread vol.",
 vol_src="Measured: AUDUSD/NZDUSD leg vols at 1440min are 68.7 and 68.5bps; the spread is far less volatile, ~230bps over a 15-day hold.",
 falsifier="Spread divergences under stable correlation do not converge.",
 spurious="Selecting the two pair-relationships after knowing which ones held together is selection on the outcome. These two are chosen on the economic grounds of shared commodity and shared European exposure, and must be fixed before testing.",
 kill="Convergence absent, or the relationship breaks structurally (correlation falls below 0.5 for a quarter), which invalidates the premise rather than the parameters."),

dict(id=35, slot="38", name="Synthetic cross divergence", fam="F6",
 mech="A cross rate must equal the ratio of its two USD legs or a triangular arbitrage exists. At sub-second horizons this is enforced by HFT. At the 1-minute horizon the residual should be zero, so this spec is a test of whether any exploitable residual survives at the frequency we can actually trade. The honest expectation is that it does not.",
 rule="Every minute compute the synthetic EURGBP from EURUSD/GBPUSD and compare to the quoted EURGBP. Enter when the divergence exceeds 3bps; exit on convergence below 1bp or after 30 minutes.",
 T=252 * 10, edge=0.5, vol=6.8, pairs=["EURUSD", "GBPUSD", "EURGBP"], hours=WD(H_LON + H_OVL), legs=3,
 edge_src="First principles, with a strong prior that the true edge is ~0 at 1-minute frequency because triangular arbitrage is the most heavily contested trade in FX. 3bps is the entry threshold, i.e. an upper bound.",
 vol_src="Measured: 15min majors-basket std 6.8bps.",
 falsifier="Divergences above 3bps at 1-minute sampling are artifacts of non-synchronous bar timestamps rather than tradeable dislocations.",
 spurious="Almost certainly the entire signal: three separate 1m bar series with independent last-print timestamps will show apparent divergence whenever one leg is stale. This is a data-artifact detector as much as a strategy.",
 kill="Divergences do not survive synchronised-timestamp construction, or the three-leg cost (which includes the unmeasured EURGBP fallback) exceeds the gross edge."),

dict(id=36, slot="3", name="TSMOM portfolio (vol-scaled re-form)", fam="F6",
 mech="Re-form of a naive-only slot. The naive version took an equal-weight sign-of-return signal, which lets the highest-volatility pairs dominate realized risk and turns a portfolio claim into a bet on a few pairs. The re-form scales each pair's position by inverse realized volatility and targets portfolio-level rather than pair-level risk, so the diversification the mechanism actually claims is realised. The mechanism itself is unchanged slow information diffusion.",
 rule="Monthly. For each G10 pair, signal = sign of the 12-month return. Position = signal / realized 60-day vol, scaled so the portfolio targets 10% annualized vol. Rebalance monthly.",
 T=12 * 10, edge=38.0, vol=430.0, pairs=G10, hours=WD(H_OVL), legs=10,
 edge_src="Derived from literature: time-series momentum in FX reports net Sharpe ~0.3-0.5. Backed out at T=120 and a 1-month rebalance.",
 vol_src="Measured: scaled daily std to a 21-day hold and aggregated with partial diversification -> ~430bps portfolio-level.",
 falsifier="Vol-scaling does not change the portfolio's realized risk concentration versus equal weight.",
 spurious="Vol-scaling reliably improves Sharpe mechanically without adding any predictive content; attributing that improvement to the momentum mechanism would be a category error.",
 kill="Literature-implied Sharpe below the bar -- route to combination."),

# ------------------------------------------------------- F7 lead-lag / spread
dict(id=37, slot="41", name="High-frequency lead-lag", fam="F7",
 mech="The most liquid pair in a correlated set incorporates common information first because it is where informed participants execute; less liquid correlated pairs follow with a lag measured in seconds to minutes. Trading the laggard on the leader's move captures the propagation. The other side is the laggard's slower participants. It persists only if the lag exceeds our execution latency, which at 1-minute sampling is the binding question.",
 rule="On 1min bars, when EURUSD moves more than 2.5 std of its 1min distribution, enter USDCHF in the corresponding direction (inverse sign) at the next bar open; exit after 5 minutes.",
 T=252 * 20, edge=0.9, vol=4.4, pairs=["USDCHF"], hours=WD(H_LON + H_OVL), legs=1,
 edge_src="First principles: residual propagation at 1min. 0.9bps is ~20% of the 5min std, and is knowingly optimistic given that this lag is the single most contested in FX.",
 vol_src="Measured: 5min majors-basket std 4.4bps.",
 falsifier="EURUSD's 1min move has no incremental predictive power for USDCHF's NEXT minute beyond the contemporaneous correlation.",
 spurious="Contemporaneous correlation leaking into the next bar through non-synchronous timestamps would create an apparent lead-lag that is pure artifact. This is the same failure mode as spec 35.",
 kill="No incremental predictability at a 1-bar execution lag, or cost exceeds the gross edge -- at ~5000 trades/year the cost term is decisive."),

dict(id=38, slot="45", name="Metals-implied FX", fam="F7",
 mech="Gold is priced in dollars and trades nearly 24 hours, and it responds to real-rate and dollar-debasement news. Commodity currencies (AUD, CAD, NZD) share exposure to the same global-growth and dollar factors but trade in thinner books outside their local hours. A gold move therefore leads the commodity currencies when those currencies' local markets are closed. The other side is the currency's thin overnight book.",
 rule="During 00:00-06:00 UTC, when XAUUSD moves more than 2.0 std of its 60min distribution, enter AUDUSD in the same direction at the next bar; exit after 120 minutes.",
 T=200, edge=2.0, vol=17.5, pairs=["AUDUSD"], hours=WD([1, 2, 3, 4, 5]), legs=1,
 edge_src="First principles: shared factor with asynchronous liquidity. 4bps is ~23% of the 120min majors std, reflecting a genuinely thin window.",
 vol_src="Measured: 120min majors-basket std 17.5bps; AUDUSD Tokyo-hours 60min vol is 15.0bps, consistent.",
 falsifier="Gold moves in Asian hours do not predict AUD beyond contemporaneous correlation.",
 spurious="AUD and gold are both risk-on assets, so the relation may be entirely contemporaneous with no lead. The test is strictly whether the NEXT bar is predictable.",
 kill="No incremental predictability at a 1-bar lag."),

dict(id=39, slot="36", name="Scandi triangle", fam="F7",
 mech="NOK and SEK are driven by a common Nordic factor plus idiosyncratic oil (NOK) and domestic-rate (SEK) exposure. Constructing the triangle across EURNOK, EURSEK and the implied NOKSEK isolates a residual that should be stationary if the common factor dominates. Displacement of the residual reflects one-sided flow in the thinnest G10 currencies and should revert. The other side is a dealer with unwanted Nordic inventory.",
 rule="Compute the residual of log(EURNOK) - log(EURSEK) against its 60-day mean. Enter against |z| > 2.0; exit on |z| < 0.5 or 10 days.",
 T=30, edge=40.0, vol=290.0, pairs=["EURNOK", "EURSEK"], hours=WD(H_LON + H_OVL), legs=2,
 edge_src="First principles: thin-market residual reversion. 70bps is ~24% of the 10-day spread vol, reflecting slow correction in capacity-constrained currencies.",
 vol_src="Measured: EURNOK and EURSEK 1440min std ~72 and ~68bps; the spread over a 10-day hold is ~290bps.",
 falsifier="The residual is not stationary, i.e. NOK and SEK have genuinely diverged on oil rather than temporarily displaced.",
 spurious="Oil is a real, persistent driver of NOK that SEK does not share. A 'reversion' spec that is actually short an oil trend will look stationary until it is not, and the failure will be concentrated in one large episode.",
 kill="Residual fails a stationarity test on rolling windows, or the two-leg cost (EURNOK 4.32 + EURSEK 3.70bps) exceeds the gross edge."),

# ------------------------------------------------------- F8 cross-asset metals
dict(id=40, slot="43", name="Gold/silver ratio (regime-conditioned re-form)", fam="F8",
 mech="Re-form of a naive-only slot. The naive version traded the raw gold/silver ratio as a stationary series, which it is not: the ratio has a secular industrial-demand trend that swamps the mean-reverting component. The re-form conditions on the ratio's own volatility regime, trading reversion only when the ratio's realized vol is in its lower tercile, on the premise that high-vol episodes are the structural repricings that break stationarity. Different functional form, same underlying precious-metals substitution mechanism.",
 rule="Daily. Compute the log gold/silver ratio z-score against its 120-day mean. When the ratio's 60-day realized vol is in the bottom tercile of its 3-year history and |z| > 2.0, enter against the deviation; exit on |z| < 0.5, on the vol regime leaving the bottom tercile, or after 20 days.",
 T=15, edge=180.0, vol=620.0, pairs=METAL, hours=WD(H_OVL), legs=2,
 edge_src="First principles: conditioned reversion in a substitution relationship. 180bps is ~29% of the 20-day ratio vol.",
 vol_src="Measured: XAUUSD 1440min std 102.7bps, XAGUSD 162.2bps; the ratio over a 20-day hold is ~620bps.",
 falsifier="The low-vol regime does not exhibit more stationarity in the ratio than the high-vol regime.",
 spurious="Silver's measured round-trip cost is 10.41bps, by far the widest in the set, and the two-leg cost is ~12.4bps. A mid-quote result would look strong and be materially eroded. Also, only ~15 trades/year makes this extremely small-sample.",
 kill="No regime difference in stationarity, or fewer than 40 independent trades in the full history."),

dict(id=41, slot="44", name="Non-USD gold momentum", fam="F8",
 mech="Gold priced in a non-USD currency isolates that currency's debasement and real-rate story from the dollar's. When gold rises in EUR terms, it signals euro-specific real-rate or credibility deterioration that should subsequently show up in EURUSD. The other side is participants who watch only USD gold. It persists because the construct requires holding two exposures.",
 rule="Daily. Compute XAU/EUR = XAUUSD / EURUSD. When its 60-day return exceeds its 250-day 80th percentile, short EURUSD; when below the 20th, go long. Hold 20 days or until the signal exits the tail.",
 T=20, edge=42.0, vol=260.0, pairs=["EURUSD", "XAUUSD"], hours=WD(H_OVL), legs=2,
 edge_src="First principles: currency-specific debasement signal. 42bps is ~16% of the 20-day EURUSD vol.",
 vol_src="Measured: EURUSD 1440min std 50.2bps scaled to a 20-day hold -> ~225bps; with the gold leg, ~260bps.",
 falsifier="XAU/EUR momentum has no predictive power for EURUSD beyond USD-gold momentum alone.",
 spurious="XAU/EUR mechanically contains EURUSD, so a 'prediction' of EURUSD from XAU/EUR can be pure algebra rather than information. The control against USD-gold-only is essential.",
 kill="No incremental power over USD gold, meaning the non-USD construction adds nothing."),

dict(id=42, slot="46", name="Gold as risk-regime filter", fam="F8",
 mech="Gold rallies during risk aversion and real-rate declines. Carry strategies fail precisely in risk-off episodes, so gold's trend is a candidate real-time state variable for when to be out of carry. The mechanism is not a new source of return but a conditioning variable on a known one: crash risk is what carry is compensated for, so an indicator that anticipates crashes should improve the payoff profile even if not the mean.",
 rule="Daily. Run an equal-weight G10 carry basket (long 3 highest-yield, short 3 lowest-yield by overnight swap). Scale exposure to zero whenever XAUUSD's 20-day return exceeds its 250-day 85th percentile; otherwise full exposure. Monthly rebalance of the basket.",
 T=12 * 6, edge=40.0, vol=430.0, pairs=G10, hours=WD(H_OVL), legs=6,
 edge_src="Derived from literature: G10 carry net Sharpe ~0.4-0.6 historically and lower post-2010. Backed out at T=72 and a 1-month hold.",
 vol_src="Measured: scaled to a 21-day hold with partial diversification -> ~430bps.",
 falsifier="The gold filter does not reduce carry drawdowns in known risk-off episodes (2011, 2015, 2020, 2022).",
 spurious="A filter tested on the same crises it was designed around is fitted to four observations. The honest test is whether it would have been out BEFORE each crash, not during.",
 kill="Filter improves in-sample drawdown but not out-of-sample, or literature-implied Sharpe below the bar -- route to combination."),

dict(id=43, slot="47", name="Silver beta amplification", fam="F8",
 mech="Silver behaves as a higher-beta version of gold with respect to the same real-rate and dollar factors, because its smaller market absorbs the same macro flow with larger price impact. If gold leads the commodity-currency complex (spec 38), silver should provide an amplified and therefore earlier-detectable version of the same signal. The other side is the thinner silver book.",
 rule="Daily. When XAGUSD's 5-day return exceeds 2.0x XAUUSD's 5-day return and both are positive, go long AUDUSD; on the mirror, go short. Hold 10 days.",
 T=25, edge=48.0, vol=310.0, pairs=["AUDUSD", "XAGUSD"], hours=WD(H_OVL), legs=2,
 edge_src="First principles: amplified common-factor signal. 48bps is ~15% of the 10-day AUDUSD vol.",
 vol_src="Measured: AUDUSD 1440min std 68.7bps scaled to a 10-day hold -> ~217bps; with the silver leg, ~310bps.",
 falsifier="Silver's excess move over gold has no predictive content for AUD beyond gold's own move.",
 spurious="Silver is far noisier than gold, so 'silver outperforming gold' is frequently just silver's idiosyncratic noise. The 2.0x threshold selects noise as often as signal.",
 kill="No incremental power over the gold-only signal of spec 38."),

# ------------------------------------------------------------ F9 carry / swap
dict(id=44, slot="15", name="Vol-targeted carry basket (drawdown-conditioned re-form)", fam="F9",
 mech="Re-form of a naive-only slot. The naive version targeted constant volatility, which is the wrong risk axis for carry: carry's risk is crash skew, not variance, and vol-targeting actually increases exposure just before crashes because carry crashes follow low-vol periods. The re-form conditions on the basket's own drawdown state instead, cutting exposure after the basket itself begins to break. Different risk functional, same carry mechanism.",
 rule="Monthly G10 carry basket (long 3 highest, short 3 lowest overnight swap). Exposure = full when the basket's 60-day drawdown is under 3%, halved between 3% and 6%, zero above 6%. Re-enter when drawdown recovers below 3%.",
 T=12 * 6, edge=40.0, vol=430.0, pairs=G10, hours=WD(H_OVL), legs=6,
 edge_src="Derived from literature: G10 carry net Sharpe ~0.4-0.6 pre-2010, materially lower since. Backed out at T=72 and a 1-month hold.",
 vol_src="Measured: scaled to a 21-day hold with partial diversification -> ~430bps.",
 falsifier="Drawdown-conditioning does not reduce the basket's left-tail relative to vol-targeting.",
 spurious="Any stop-loss overlay improves backtested drawdown by construction while reducing mean return; reporting the drawdown improvement without the return cost would be selective.",
 kill="Literature-implied Sharpe below the bar -- route to combination."),

dict(id=45, slot="17", name="Swap-aware swing bias", fam="F9",
 mech="Retail and small-institutional platforms charge asymmetric overnight swap: the debit for holding the negative-carry side typically exceeds the credit for the positive side. That asymmetry creates a systematic incentive to hold positions in the positive-carry direction and to avoid multi-day holds against carry. A directional swing rule that breaks ties in favour of positive carry should therefore keep more of its gross edge. The other side is the platform earning the spread.",
 rule="Daily. Take a 20/60 MA crossover signal on G10 pairs, but suppress any signal that would hold against the positive-carry direction for more than 3 days. Exit on opposite cross or after 15 days.",
 T=35, edge=28.0, vol=230.0, pairs=G10, hours=WD(H_OVL), legs=1,
 edge_src="Derived from literature as in spec 23, plus the swap asymmetry as a cost reduction rather than an alpha source. 28bps backed out at T=35 and a ~15-day hold.",
 vol_src="Measured: 1440min std 57.9bps scaled to a ~15-day hold -> ~230bps.",
 falsifier="Suppressing negative-carry holds does not improve net returns versus the unfiltered crossover.",
 spurious="The swap asymmetry is a real cost saving, but the spec would then be a cost improvement on a trend rule whose own edge is below the bar. Improving the cost of a losing strategy does not make it a winner.",
 kill="Underlying trend rule's if-true Sharpe below the bar, which the screen confirms -- route to combination."),

# ------------------------------------------------------ F10 calendar/liquidity
dict(id=46, slot="31", name="Day-of-week effect", fam="F10",
 mech="Weekly institutional processes are not uniform across weekdays: Monday reprices weekend information on thin books, mid-week carries the heaviest scheduled-data load, and Friday carries pre-weekend squaring. If any systematic return pattern by weekday survives, it should be attributable to one of these flow processes rather than to the calendar itself. This spec is stated with an explicitly weak prior: a calendar effect without an identified flow is a data-mining artifact by default.",
 rule="Daily. Long EURUSD from Monday 07:00 UTC to Monday 20:00 UTC; flat otherwise. Fixed, single weekday, chosen a priori as the weekend-repricing day rather than selected from the data.",
 T=52, edge=3.0, vol=34.3, pairs=["EURUSD"], hours=WD(H_LON + H_OVL), legs=1,
 edge_src="First principles with a weak prior. 3bps is ~9% of the 480min majors std, and the honest expectation is zero.",
 vol_src="Measured: 480min majors-basket std 34.3bps.",
 falsifier="Monday session returns are indistinguishable from other weekdays.",
 spurious="This is the archetypal p-hacking family: with 5 weekdays x 2 directions x 10 pairs there are 100 combinations, and roughly 5 will pass at the 5% level by chance. Fixing one pair and one weekday in advance is the only defence, and even then the prior is weak.",
 kill="Insignificant, which is the expected outcome; and if significant, it must be checked against the other four weekdays to confirm it is not the best of five."),

dict(id=47, slot="34", name="Holiday thin-liquidity reversion", fam="F10",
 mech="On days when a major financial centre is closed, the affected currency's book is materially thinner while the rest of the world continues to trade. Order flow that must transact meets less depth and displaces price further than it would on a normal day; the displacement corrects when the centre reopens. The other side is participants who cannot wait for the holiday to end. It persists because holidays are few and the positions must be held across a low-liquidity period.",
 rule="On US market holidays that are not FX holidays, measure the 12:00-20:00 UTC return in EURUSD and GBPUSD. If |return| exceeds 1.0x the trailing 20-day std of that window, enter against it at 20:00 UTC and exit at 16:00 UTC the following business day.",
 T=9 * 2, edge=12.0, vol=57.9, pairs=["EURUSD", "GBPUSD"], hours=WD(H_NYPM), legs=1,
 edge_src="First principles: amplified impact on thin books. 12bps is ~21% of the daily majors std, justified by genuinely reduced depth.",
 vol_src="Measured: 1440min majors-basket std 57.9bps.",
 falsifier="Holiday-session displacements are not corrected on reopening.",
 spurious="Roughly 9 US holidays a year across 2 pairs is ~18 trades/year and ~270 in the full history, but holidays cluster seasonally so the effective independence is lower. A handful of episodes will dominate.",
 kill="Fewer than 40 effectively independent observations, or no correction versus a matched non-holiday control."),

dict(id=48, slot="NOVEL", name="Post-holiday liquidity restoration", fam="F10",
 mech="The counterpart to spec 47. When a major centre reopens after a holiday or an extended break, accumulated orders that could not be executed arrive together, producing a concentrated one-directional flow in the first hours of the reopening. Unlike the holiday displacement itself, this flow is informed accumulation rather than noise, so it should CONTINUE rather than revert within the session. Proposing both signs at different points in the holiday cycle is deliberate: they are different flow processes, not a hedge.",
 rule="On the first session after a US market holiday, measure the 12:00-14:00 UTC return; enter in the same direction at 14:00 UTC; exit at 20:00 UTC.",
 T=9 * 2, edge=5.0, vol=24.5, pairs=["EURUSD", "GBPUSD"], hours=WD([14, 15, 16]), legs=1,
 edge_src="First principles: concentrated release of accumulated orders. 5bps is ~20% of the 240min majors std.",
 vol_src="Measured: 240min majors-basket std 24.5bps.",
 falsifier="Reopening sessions show no more within-session continuation than ordinary sessions.",
 spurious="With ~18 trades/year this is small-sample, and it shares its event calendar with spec 47, so the two are not independent evidence about holidays.",
 kill="No excess continuation versus a matched ordinary-session control."),

dict(id=49, slot="NOVEL", name="Intraday session-open range persistence", fam="F10",
 mech="Gao-Han-Li-Zhou (2018) document intraday momentum in equity index futures: the first half-hour return predicts the last half-hour return, attributed to informed traders splitting orders across the session and to late-day rebalancing by liquidity providers. The FX analog is the London session: institutional programs begun at the open are worked through the day and completed before the London close. The other side is the program's counterparty.",
 rule="Measure the EURUSD, GBPUSD and USDJPY return over 07:00-08:00 UTC. Enter in the same direction at 15:00 UTC; exit at 16:30 UTC. One trade per pair per day.",
 T=252 * 3, edge=1.3, vol=12.5, pairs=MAJ4[:3], hours=WD([15, 16]), legs=1,
 edge_src="Gao et al. report a robust first-half-hour to last-half-hour relation in equity futures. The FX transmission is untested; 1.8bps is ~14% of the 60min majors std, a modest read of the analog.",
 vol_src="Measured: 60min majors-basket std 12.5bps.",
 falsifier="The London first-hour return does not predict the London last-hour return.",
 spurious="The effect is documented in a different asset class with a different market structure (a single central limit order book with a defined close). FX has no close, so the mechanism's key ingredient -- a deadline -- is weaker.",
 kill="No relation, or the relation present only in the pre-2015 sample."),
]
