server:
  http_listen_port: 9080
  http_listen_address: 127.0.0.1
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: journald
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
    pipeline_stages:
      - match:
          selector: '{unit=~"homeguard-.*"}'
          stages:
            - regex:
                expression: '\[(?P<level>[A-Z]+)\]'
            - labels:
                level:
