"""Shared Gate 0.3 driver helpers for the futures-retest sleeve drivers
(scripts/backtest_scripts/sp_retest_*.py).

Every sp_retest_<sleeve>.py driver wraps an existing, already-gated `run_*`
sleeve function (each of which computes its own PSR/DSR/PBO gate via
gate_return_stream / gate_session_stream / gate_convergence and persists
returns.csv + gate.json to its own output_dir) in `RunStatus`
(src/utils/run_status.py, methodology Section 10 / strategy-pipeline rules
"Run-status logging"), appends one row to output/experiments.duckdb
(methodology Section 9.3), and writes a
docs/reports/futures/<STRAT>_READINESS.md verdict report -- mirroring the
pattern already established in
scripts/backtest_scripts/run_carver_walkforward.py::main().

Consult docs/methodology/backtesting.md Sections 1, 2, 3, 4, 9, 11, 12 before
using or modifying these helpers.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

from src.backtesting.walkforward_common import _verdict
from src.utils import logger


def verdict_input(gate: Dict[str, Any], sharpe_1_5x: Optional[float] = None) -> Dict[str, Any]:
    """Adapt a gate_return_stream / gate_session_stream / gate_convergence
    result dict (keys: oos_sharpe, psr, dsr, pbo, ...) into the shape
    `walkforward_common._verdict` expects, which additionally requires
    `oos_sharpe_1_5x_cost`.

    Sleeves that only ran a single (1x) cost leg pass `sharpe_1_5x=None`; in
    that case the 1.5x cost-sensitivity gate cannot be honestly evaluated, so
    this reports NaN (a WEAK/INCONCLUSIVE-leaning verdict) rather than
    defaulting to a value that would make the combined gate easier to pass.
    """
    out = dict(gate)
    out["oos_sharpe_1_5x_cost"] = sharpe_1_5x if sharpe_1_5x is not None else float("nan")
    return out


def write_readiness_report(strategy_name: str, title: str, gate: Dict[str, Any],
                            report_path: str, extra_notes: str = "",
                            sharpe_1_5x: Optional[float] = None,
                            run_id: Optional[str] = None) -> str:
    """Write a docs/reports/futures/<STRAT>_READINESS.md verdict report for a
    Gate 0.3 sleeve driver run. Returns the written path."""
    vi = verdict_input(gate, sharpe_1_5x)
    verdict = _verdict(vi)

    def _fmt(key: str, default: str = "n/a") -> str:
        v = gate.get(key)
        if v is None:
            return default
        if isinstance(v, float):
            return f"{v:.4f}"
        return str(v)

    content = f"""# {title} Readiness Report (Gate 0.3 retest driver)

Generated by `scripts/backtest_scripts/sp_retest_common.py::write_readiness_report`
on behalf of `{strategy_name}`, part of the futures campaign comprehensive
retest driven by
`docs/strategies/research/20260711_FUTURES_RETEST_TODO.md`.

## Metrics

| Metric | Value |
|---|---|
| OOS Sharpe (1x cost) | {_fmt('oos_sharpe')} |
| OOS Sharpe (1.5x cost) | {f"{vi['oos_sharpe_1_5x_cost']:.4f}" if vi['oos_sharpe_1_5x_cost'] == vi['oos_sharpe_1_5x_cost'] else 'not run (1x cost leg only)'} |
| PSR | {_fmt('psr')} |
| DSR (n_trials={_fmt('trial_count')}) | {_fmt('dsr')} |
| PBO | {_fmt('pbo')} |
| n_windows | {_fmt('n_windows')} |
| n_oos | {_fmt('n_oos', _fmt('n_oos_days'))} |
| skew | {_fmt('skew')} |
| kurtosis | {_fmt('kurtosis', _fmt('kurtosis_pearson'))} |
| n_trades | {_fmt('n_trades')} |
| registry run_id | {run_id} |

## Verdict

{verdict}

{extra_notes}
"""
    out_path = Path(report_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    logger.info(f"[{strategy_name}] wrote {out_path}; verdict={verdict}")
    return str(out_path)


def convergence_exit_summary(trades_path: str) -> str:
    """Honest Section 11 exit-diagnostic summary for the convergence-spread
    sleeves (#31 calendar, #32/#33 processing, #34 ratio).

    `src.backtesting.spreads.convergence.SpreadTrade` does NOT persist an
    `exit_reason` field (only entry_date, exit_date, direction, entry_z,
    exit_z, ret) -- a code-review finding from the Gate 0.3 build (2026-07-11):
    an earlier version of these drivers claimed a converge/structural/time-stop
    breakdown that the underlying engine cannot produce, which would have
    silently printed a false "no exit_reason" line while the docstring
    asserted the diagnostic was satisfied. This function reports only what
    `trades.csv` actually contains -- direction mix and holding-period
    distribution -- and says so explicitly, rather than fabricating an
    exit-reason breakdown. Extending `SpreadTrade`/`simulate_convergence` to
    emit `exit_reason` (converged/broke/timed) is a separate, tracked
    follow-up, not silently worked around here.
    """
    import pandas as pd

    try:
        df = pd.read_csv(trades_path)
    except (FileNotFoundError, pd.errors.EmptyDataError):
        return "No trades.csv / no closed trades."
    if df.empty:
        return "trades.csv is empty -- no closed trades."
    n = len(df)
    long_n = int((df["direction"] > 0).sum()) if "direction" in df.columns else None
    short_n = int((df["direction"] < 0).sum()) if "direction" in df.columns else None
    hold_days = None
    if {"entry_date", "exit_date"} <= set(df.columns):
        hold_days = (pd.to_datetime(df["exit_date"]) - pd.to_datetime(df["entry_date"])).dt.days
    summary = (
        f"n_trades={n}"
        + (f", long={long_n}, short={short_n}" if long_n is not None else "")
        + (f", median_hold_days={hold_days.median():.1f}, max_hold_days={hold_days.max():.0f}"
           if hold_days is not None and len(hold_days) else "")
    )
    return (summary + ". NOTE: SpreadTrade does not persist exit_reason -- "
            "converge/structural-stop/time-stop cannot be distinguished from "
            "trades.csv alone (a Section 11.9 gap in the convergence engine, "
            "tracked separately, not fabricated here).")


def append_registry_row(strategy_name: str, gate: Dict[str, Any], **kwargs) -> Optional[str]:
    """Best-effort registry append (methodology Section 9.3). Logs and
    returns None on failure rather than raising -- mirrors the
    walk_forward_carver pattern: a registry-append failure must not discard
    an otherwise-completed, already-persisted (returns.csv/gate.json)
    backtest result."""
    try:
        from src.experiments import append_run

        metrics = {k: v for k, v in gate.items()
                   if not isinstance(v, (list, dict)) and not k.startswith("gate_")}
        return append_run(
            strategy_name=strategy_name,
            agent_name=kwargs.pop("agent_name", "sp-retest-driver"),
            metrics=metrics,
            asset_class=kwargs.pop("asset_class", "futures"),
            data_frequency=kwargs.pop("data_frequency", "daily"),
            phase=kwargs.pop("phase", "walk_forward"),
            **kwargs,
        )
    except Exception as e:
        logger.error(f"[{strategy_name}] registry append_run failed (non-fatal): {e}")
        return None
